apiVersion: v1
kind: Service
metadata:
  name: intellicent-usermanagement-app
spec:
  selector:
    app: intellicent-usermanagement-app
  ports:
    - port: 8081
      targetPort: 8081
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intellicent-usermanagement-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intellicent-usermanagement-app
  template:
    metadata:
      labels:
        app: intellicent-usermanagement-app
    spec:
      containers:
        - name: intellicent-usermanagement-app
          image: xactip/intellicent-usermanagement-app:1.0
          ports:
            - containerPort: 8081
          env:
            - name: MONGO_HOST
              value: usermanagement-mongo:27018
            - name: KC_HOST
              value: keycloak-app:8099
          imagePullPolicy: Always
