apiVersion: v1
kind: Service
metadata:
  name: keycloak-app
spec:
  selector:
    app: keycloak-app
  ports:
    - port: 8099
      targetPort: 8099
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-app
  template:
    metadata:
      labels:
        app: keycloak-app
    spec:
      containers:
        - name: keycloak-app
          image: quay.io/keycloak/keycloak:21.0
          ports:
            - containerPort: 8099
          env:
            - name: KC_HTTP_PORT
              value: "8099"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://keycloak-postgres/keycloak_db
            - name: KC_DB_URL_PORT
              value: "5432"
            - name: KC_DB_USERNAME
              value: keycloak_user
            - name: KC_DB_PASSWORD
              value: keycloak_pass
            - name: KC_DB_SCHEMA
              value: public
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
          args:
            - "start"
            - "--log-level=DEBUG"
          imagePullPolicy: Always
